### ISSUE TITLE
Support lsp integration

### ISSUE THREAD

**Issue by narutohahahaha** [ryu-ichiroh/vim-cspell#10]
Hi there,

I want to ask would it be possible to support LSP integration? Something like a lspconfig for cspell?

**Comment by ryicoh** [comment]
@narutohahahaha 
thank you for positing the issue.

I think efm-langserver is good for you.

https://github.com/mattn/efm-langserver

vim-efm-langserver-settings makes you easy to integrate with cspell.

https://github.com/tsuyoshicho/vim-efm-langserver-settings/pull/156
